# Generated by Django 4.2.3 on 2023-07-18 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [('orders', '0003_alter_order_delivery_alter_order_user')]

    operations = [
        migrations.RemoveField(model_name='delivery', name='created'),
        migrations.RemoveField(model_name='delivery', name='phone'),
        migrations.RemoveField(model_name='delivery', name='updated'),
        migrations.AddField(
            model_name='delivery',
            name='comment',
            field=models.CharField(blank=True, verbose_name='Комментарий к доставек'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='datetime_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время доставки от'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='datetime_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время доставки до'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='elevator',
            field=models.BooleanField(default=False, verbose_name='Наличие лифта'),
        ),
    ]
