# Generated by Django 4.2.2 on 2023-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('product', '0008_alter_collection_options_alter_color_options_and_more')]

    operations = [
        migrations.CreateModel(
            name='FurniturePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'main_image',
                    models.ImageField(
                        default='products/noimage_detail.png', upload_to='', verbose_name='Фотография продукта'
                    ),
                ),
                (
                    'first_image',
                    models.ImageField(
                        blank=True,
                        default='products/noimage_detail.png',
                        upload_to='',
                        verbose_name='Фотография продукта',
                    ),
                ),
                (
                    'second_image',
                    models.ImageField(
                        blank=True,
                        default='products/noimage_detail.png',
                        upload_to='',
                        verbose_name='Фотография продукта',
                    ),
                ),
                (
                    'third_image',
                    models.ImageField(
                        blank=True,
                        default='products/noimage_detail.png',
                        upload_to='',
                        verbose_name='Фотография продукта',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Изображение мебели',
                'verbose_name_plural': 'Изображения мебели',
                'ordering': ('pk',),
            },
        ),
        migrations.RemoveField(model_name='product', name='image'),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='non_type', max_length=20, verbose_name='Тип мебели'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='furnituredetails',
            name='furniture_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип конструкции'),
        ),
    ]
