# Generated by Django 4.2.2 on 2023-07-18 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('product', '0008_alter_collection_options_alter_color_options_and_more')]

    operations = [
        migrations.CreateModel(
            name='FurniturePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'main_image',
                    models.ImageField(
                        default='products/noimage_detail.png', upload_to='', verbose_name='Фотография продукта'
                    ),
                ),
                (
                    'first_image',
                    models.ImageField(
                        blank=True,
                        default='products/noimage_detail.png',
                        upload_to='',
                        verbose_name='Фотография продукта',
                    ),
                ),
                (
                    'second_image',
                    models.ImageField(
                        blank=True,
                        default='products/noimage_detail.png',
                        upload_to='',
                        verbose_name='Фотография продукта',
                    ),
                ),
                (
                    'third_image',
                    models.ImageField(
                        blank=True,
                        default='products/noimage_detail.png',
                        upload_to='',
                        verbose_name='Фотография продукта',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Изображение мебели',
                'verbose_name_plural': 'Изображения мебели',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название типа мебели')),
            ],
            options={'verbose_name': 'Тип мебели', 'verbose_name_plural': 'Типы мебели', 'ordering': ('name',)},
        ),
        migrations.RemoveField(model_name='product', name='image'),
        migrations.AddField(
            model_name='product',
            name='legs_material',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products_legs',
                to='product.material',
                verbose_name='Материал опор',
            ),
        ),
        migrations.AlterField(
            model_name='furnituredetails',
            name='furniture_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип конструкции'),
        ),
        migrations.RemoveField(model_name='product', name='material'),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products',
                to='product.furniturepicture',
                verbose_name='Изображения товара',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products',
                to='product.producttype',
                verbose_name='Тип мебели',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products',
                to='product.material',
                verbose_name='Материал основания',
            ),
        ),
    ]
