# Generated by Django 4.2.2 on 2023-07-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('product', '0008_alter_collection_options_alter_color_options_and_more')]

    operations = [
        migrations.CreateModel(
            name='FurniturePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'image',
                    models.ImageField(
                        default='products/noimage_detail.png', upload_to='', verbose_name='Фотография продукта'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Изображение мебели',
                'verbose_name_plural': 'Изображения мебели',
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Не установлен', max_length=20, verbose_name='Тип мебели'),
        ),
        migrations.AlterField(
            model_name='furnituredetails',
            name='furniture_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип конструкции'),
        ),
        migrations.RemoveField(model_name='product', name='image'),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(
                related_name='products', to='product.furniturepicture', verbose_name='изображения'
            ),
        ),
    ]
