# Generated by Django 4.2.2 on 2023-07-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('product', '0009_furniturepicture_remove_product_image_and_more')]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='product.furniturepicture',
                verbose_name='изображения',
            ),
            preserve_default=False,
        )
    ]
