# Generated by Django 4.2.3 on 2023-07-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('product', '0009_furniturepicture_producttype_remove_product_image_and_more')]

    operations = [
        migrations.AlterField(
            model_name='furnituredetails',
            name='furniture_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип'),
        )
    ]
