version: '3'

volumes:
  online_furniture_store_dev_prod_postgres_data: {}
  online_furniture_store_dev_prod_postgres_data_backups: {}
  dev_prod_django_media: {}
  dev_prod_django_static: {}

services:
  django: &django
    image: onlinefurniturestore/online_furniture_store_dev_prod:latest
    container_name: online_furniture_store_dev_prod_django
    build:
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - dev_prod_django_media:/var/www/django/media
      - dev_prod_django_static:/var/www/django/static
    env_file:
      - ./.env
    command: /start

  postgres:
    image: onlinefurniturestore/online_furniture_store_dev_prod_postgres:latest
    container_name: online_furniture_store_dev_prod_postgres
    restart: unless-stopped
    volumes:
      - online_furniture_store_dev_prod_postgres_data:/var/lib/postgresql/data
      - online_furniture_store_dev_prod_postgres_data_backups:/backups
    env_file:
      - ./.env

  nginx:
    image: onlinefurniturestore/online_furniture_store_dev_prod_nginx:latest
    restart: unless-stopped
    container_name: online_furniture_store_dev_prod_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./compose/dev_prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./compose/dev_prod/nginx/ssl-params.conf:/etc/nginx/ssl-params.conf
      - dev_prod_django_media:/usr/share/nginx/media:ro
      - dev_prod_django_static:/usr/share/nginx/static:ro
      - ./logs/:/var/log/nginx/
    env_file:
      - ./.env
